# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build Site

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    # fix git protocol https://github.com/orgs/community/discussions/26648#discussioncomment-3252721
    - run: git config --global url."git@github.com:".insteadOf git://github.com/
    - name: Install dependencies
      run: npm ci --ignore-scripts
    - name: Check formatting
      run: npm run check-format
    - name: Build
      run: npm run build
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/master'
      uses: JamesIves/github-pages-deploy-action@v4.5.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        folder: dist
